version: '3'

services:
    traefik:
        image: traefik:v2.3
        container_name: traefik
        command:
                #        - "--api.insecure=true"
        - "--accesslog=true"
        - "--providers.docker=true"
        - "--providers.docker.exposedbydefault=false"
        - "--entrypoints.websecure.address=:443"
        - "--entrypoints.web.address=:80"
        - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
        - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
        - "--entrypoints.web.http.redirections.entrypoint.permanent=true"
        - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
        - "--certificatesresolvers.myresolver.acme.email=${EMAIL}"
        - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
        ports:
        - "443:443"
        volumes:
        - "./letsencrypt:/letsencrypt"
        - "/var/run/docker.sock:/var/run/docker.sock"
        - "/var/log/traefik/:/var/log"
        
    mariadb:
        image: mariadb:10
        container_name: mariadb
        environment:
            - MYSQL_ROOT_PASSWORD=${DBPASSWORD}
            - MYSQL_DATABASE=${DBNAME}
        volumes:
            - "./mariadb:/var/lib/mysql"
      
    scpushack:
        image: nherbaut/scpushack
        container_name: scpushack
        environment:
            - API_KEY=${API_KEY}
            - SQLALCHEMY_DATABASE_URI=mysql://root:root@mariadb/scpushack
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.scpushack.tls.certresolver=myresolver"
            - "traefik.http.routers.scpushack.rule=host(`scpushack.nextnet.top`)"
        expose:
            - "5000"
        volumes:
            - "./scpushash/:/var/scpushack/history:rw"
        depends_on:
            - mariadb



    php:
        build: debian-based
        container_name: php
        volumes:
                - "./debian-based/www:/var/www:rw"
                - "./sync:/drupal-config/stream-for-good.miage.dev/sync:rw"
        depends_on:
                - mariadb
                - traefik
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.php.tls.certresolver=myresolver"
            - "traefik.http.routers.php.rule=host(`stream-for-good.miage.dev`)"
            - "traefik.http.routers.php.entrypoints=websecure"
            - "traefik.http.services.php.loadbalancer.server.port=80"
            - "traefik.http.middlewares.https-redirect.headers.sslredirect=true"
            - "traefik.http.middlewares.https-redirect.headers.sslproxyheaders.X-Forwarded-Proto=https"
            - "traefik.http.routers.php.middlewares=https-redirect"
        expose:
            - "80"
            
