version: '3'

services:
    traefik:
        image: traefik:v2.3
        container_name: traefik
        command:
                #        - "--api.insecure=true"
                #        - "--accesslog=true"
        - "--providers.docker=true"
        - "--providers.docker.exposedbydefault=false"
        - "--entrypoints.websecure.address=:443"
        - "--entrypoints.web.address=:80"
        - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
        - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
        - "--entrypoints.web.http.redirections.entrypoint.permanent=true"
        - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
        - "--certificatesresolvers.myresolver.acme.email=${EMAIL}"
        - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
        ports:
        - "443:443"
<<<<<<< HEAD
          #        - "8080:8080"
=======
>>>>>>> 65eed4832cb3d2fac5aa88603056096422f0af57
        volumes:
        - "./letsencrypt:/letsencrypt"
        - "/var/run/docker.sock:/var/run/docker.sock"
        - "/var/log/traefik/:/var/log"
        
      
    web-nginx:
        image: nginx:stable-alpine
        container_name: web-nginx
        volumes:
            - "./docker-web/www:/usr/share/nginx/html:rw"
            - "./docker-web/log:/var/log/nginx"
            - "./docker-web/nginx.conf:/etc/nginx/nginx.conf:ro"
        depends_on:
            - web-php
            - traefik
        labels:
        - "traefik.enable=true"
        - "traefik.http.routers.web-nginx.tls.certresolver=myresolver"
        - "traefik.http.routers.web-nginx.rule=host(`nicolas-herbaut.fr`) || host(`stream-for-good.miage.dev`)"
        - "traefik.http.routers.web-nginx.entrypoints=websecure"
        - "traefik.http.services.web-nginx.loadbalancer.server.port=80"
        - "traefik.http.middlewares.https-redirect.headers.sslredirect=true"
        - "traefik.http.middlewares.https-redirect.headers.sslproxyheaders.X-Forwarded-Proto=https"
        - "traefik.http.routers.web-nginx.middlewares=https-redirect"
        expose:
            - "80"

    web-php:
        build: php
        container_name: web-php
        volumes:
            - "./docker-web/www:/script:rw"
            - "./docker-web/config:/drupal-config:rw"
        depends_on:
            - mariadb
            
    mariadb:
        image: mariadb:10
        container_name: mariadb
        environment:
            - MYSQL_ROOT_PASSWORD=${DBPASSWORD}
            - MYSQL_DATABASE=${DBNAME}
        volumes: 
            - "./mariadb:/var/lib/mysql"
